# Generated by Django 4.2.6 on 2023-11-09 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('photo', models.ImageField(upload_to='photos')),
                ('category', models.CharField(choices=[('Fiction', 'Fiction'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Science fiction', 'Science fiction'), ('History', 'History'), ('Thriller', 'Thriller'), ('Comics', 'Comics')], max_length=70)),
                ('is_available', models.BooleanField()),
                ('published', models.DateTimeField()),
                ('ISO', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django',
            },
        ),
    ]
